### ISSUE TITLE
Returning does not work without adjacent block

### ISSUE THREAD

**Issue by lorenzorota** [iRath96/splix-bot#7]
[![IMAGE ALT TEXT](http://img.youtube.com/vi/zN8FlW70BWs/0.jpg)](http://www.youtube.com/watch?v=zN8FlW70BWs "Video Title")

**Comment by iRath96** [comment]
**What causes the bug:**
1. `BotState.ADVANCING`
2. `BotState.PRE_RETURN`
3. `BotState.RETURNING` further than was previously advanced

**How to fix the bug:**
The bot needs to be aware of which block it started advancing from. If there is no adjacent block which would be hit on returning, it needs to detect this and instead turn once more (on the adjacent block) so that it hits the block it started advancing from.
